// <auto-generated />
using MeetingPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MeetingPlanner.Migrations
{
    [DbContext(typeof(MeetingContext))]
    [Migration("20180409165754_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeetingPlanner.Models.Bulletin", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("ClosingPrayerName");

                    b.Property<int>("ClosingSongNumber");

                    b.Property<string>("MeetingConductor");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<string>("OpeningPrayerName");

                    b.Property<int>("OpeningSongNumber");

                    b.HasKey("ID");

                    b.ToTable("Bulletin");
                });

            modelBuilder.Entity("MeetingPlanner.Models.Speaker", b =>
                {
                    b.Property<int>("SpeakerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BulletinID");

                    b.Property<string>("Name");

                    b.Property<string>("Topic");

                    b.HasKey("SpeakerID");

                    b.HasIndex("BulletinID");

                    b.ToTable("Speaker");
                });

            modelBuilder.Entity("MeetingPlanner.Models.Speaker", b =>
                {
                    b.HasOne("MeetingPlanner.Models.Bulletin")
                        .WithMany("Speakers")
                        .HasForeignKey("BulletinID");
                });
#pragma warning restore 612, 618
        }
    }
}
